# Generated by Django 4.2.3 on 2023-07-28 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='author',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='acceptt_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='agree_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='cancle_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='decline_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='wait_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='library',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='trade.book'),
        ),
    ]
