# Generated by Django 4.2.3 on 2023-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_library_author_remove_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='books',
        ),
        migrations.AddField(
            model_name='request',
            name='requested_books',
            field=models.ManyToManyField(related_name='requsted_books', to='trade.book'),
        ),
        migrations.AddField(
            model_name='request',
            name='sent_books',
            field=models.ManyToManyField(related_name='sent_books', to='trade.book'),
        ),
    ]
