# Generated by Django 4.2.3 on 2023-08-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_rename_language_language_languages_alter_book_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='languages',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='trade.language'),
        ),
    ]
