# Generated by Django 4.2.1 on 2023-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='sent_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='sent_books', to='exchange.book'),
        ),
    ]
