# Generated by Django 4.2.1 on 2023-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('Б/у', 'Б/у'), ('Новый', 'Новый')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Одобрено', 'Одобрено'), ('Рассматривается', 'Рассматривается'), ('Отказано', 'Отказано')], max_length=15),
        ),
    ]
