# Generated by Django 4.2.1 on 2023-08-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_remove_book_is_available_book_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(max_length=25),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('одобрено', 'Одобрено'), ('рассматривается', 'Рассматривается'), ('доступно', 'Доступно')], default='доступно', max_length=15),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_genre', to='exchange.genre'),
        ),
    ]
